#!/bin/bash

if [ $# -ne 1 ]; then
echo "Usage: commitscript <filename>"
exit 1
fi

filename="$1"

git add "$filename" || exit 1

read -p "Commit message: " message

git commit -m "$message" || exit 1

git push || exit 1

echo "Done."
